# Generated by Django 4.0.6 on 2022-07-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='film_producers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('Fecha_muerte', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Título', models.CharField(max_length=32)),
                ('País', models.CharField(max_length=20)),
                ('Duración', models.CharField(max_length=9)),
                ('Fecha_lanzamiento', models.CharField(max_length=15)),
                ('Elenco', models.CharField(max_length=200)),
                ('Sinopsis', models.TextField(help_text='Una breve descripción del contenido', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del género', max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Productores',
        ),
        migrations.AddField(
            model_name='films',
            name='Género',
            field=models.ManyToManyField(to='Productores.genre'),
        ),
        migrations.AddField(
            model_name='films',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productores.film_producers'),
        ),
    ]
